include $(TOPDIR)/rules.mk

PKG_VERSION:=1.0.0

LUCI_TITLE:=LuCI Support for Nezha Agent
LUCI_DEPENDS:=+luci-base +nezha +uuidgen

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
