include $(TOPDIR)/rules.mk

PKG_VERSION:=1.0.0

LUCI_TITLE:=LuCI Support for DDNS GO
LUCI_DEPENDS:=+luci-base +ddns-go

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
